/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'CheckboxDiscernible',
    status: 'active',
    category: 'forms',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'forms:checkbox-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'form-label',
      target: { selector: 'input[type="checkbox"]' },
      options: { mode: 'checkbox-missing-label' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Checkbox controls should have a label',
      requirement: 'Screen readers rely on properly coded and associated labels to announce the purpose of a form field. A checkbox control without an identifiable label may prevent screen reader users from completing the form.',
      recommendation: 'Add a <label> element associated with the checkbox, or use aria-label.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'RadioDiscernible',
    status: 'active',
    category: 'forms',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'forms:radio-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'form-label',
      target: { selector: 'input[type="radio"]' },
      options: { mode: 'radio-missing-label' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Radio controls should have a label',
      requirement: 'Screen readers rely on properly coded and associated labels to announce the purpose of a form field. A radio control without an identifiable label may prevent screen reader users from completing the form.',
      recommendation: 'Add a <label> element associated with the radio button, or use aria-label.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'RequiredFormFieldAriaRequired',
    status: 'active',
    category: 'forms',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '3.3.2' },
    severity: { impact: 'serious', priority: 6 },
    automation: 'heuristic',
    checks: [
      {
        id: 'forms:required-visual-indication',
        profiles: ['standards'],
        evaluator: 'form-label',
        target: { selector: 'input, select, textarea' },
        options: { mode: 'visual-required-missing-attr' },
        classification: 'potential',
      },
      {
        id: 'parity:current-link-required',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'current-link-required' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Mandatory form fields should indicate that they are required',
      requirement: 'If a field is marked as required only through visual cues, but lacks the required attribute or aria-required="true", screen readers will not announce it as mandatory. As a result, users may experience unnecessary delays or confusion when trying to submit the form.',
      recommendation: 'Add required or aria-required="true" to visually required fields.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'FormSubmitButtonMismatch',
    status: 'active',
    category: 'forms',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '3.2.2' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'deterministic',
    checks: [{
      id: 'forms:form-submit-button-mismatch',
      profiles: ['standards'],
      evaluator: 'form-relationships',
      target: { selector: 'form' },
      options: { mode: 'form-submit-button-mismatch' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Form submission controls should have type="submit"',
      requirement: 'Adding type="submit" to a control that submits a form ensures that screen readers users expect a change of context when they activate the control.',
      recommendation: 'Add type="submit" to the form submission button.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'FormContextChangeWarning',
    status: 'active',
    category: 'forms',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '3.2.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'heuristic',
    checks: [{
      id: 'forms:form-context-change-warning',
      profiles: ['standards'],
      evaluator: 'form-relationships',
      target: { selector: 'select' },
      options: { mode: 'form-context-change-warning' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Interacting with form controls should not cause a change in context without warning',
      requirement: 'Interacting with form controls shouldn\'t automatically submit a form or cause any other change in context without notifying the user in advance.',
      recommendation: 'Avoid auto-submitting forms on select change — provide an explicit submit button.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'MainNavigationMismatch',
    status: 'active',
    category: 'forms',
    standard: { version: 'Best Practice', level: 'n/a', criterion: 'n/a' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [
      {
        id: 'forms:main-navigation-mismatch',
        profiles: ['standards'],
        evaluator: 'form-relationships',
        target: { selector: 'ul, ol' },
        options: { mode: 'main-navigation-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:main-navigation-layout',
        profiles: ['commercial-parity'],
        evaluator: 'form-relationships',
        target: { selector: 'nav, [role="navigation"]', allowPluginFallback: true },
        options: { mode: 'main-navigation-layout-parity' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Main navigation should have role navigation',
      requirement: 'Main navigation elements should have role navigation to ensure that screen readers can identify them as navigation regions.',
      recommendation: 'Wrap main navigation in <nav> or add role="navigation" for screen reader landmark access.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
