/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'AltMisuse',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.1', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'deterministic',
    checks: [
      {
        id: 'general:alt-misuse',
        profiles: ['standards'],
        evaluator: 'attributes-roles',
        target: { selector: '[alt]' },
        options: { mode: 'misplaced-alt', excludeTags: ['img', 'area'] },
        classification: 'confirmed',
      },
      {
        id: 'parity:alt-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'attributes-roles',
        target: { selector: '[alt]' },
        options: {
          mode: 'misplaced-alt',
          excludeTags: ['img', 'area'],
          excludeShadowRoots: true,
        },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Elements other than image (Tag: IMG) should not have alt attribute',
      requirement: 'The alt attribute is used to provide a text alternative for images. It is not meant to be used on elements other than images and therefore will not be read using screen-readers.',
      recommendation: 'Remove alt attribute from non-image elements. Use aria-label for accessible names instead.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'IframeDiscernible',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'general:iframe-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: 'iframe' },
      options: { mode: 'iframe-missing-title' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Iframes should have a descriptive label',
      requirement: 'An iframe needs a label that describes its purpose to screen reader users.',
      recommendation: 'Add a descriptive title attribute to <iframe> elements.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'NoRoleApplication',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'general:no-role-application',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[role="application"]' },
      options: { mode: 'forbidden-role', role: 'application' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Avoid using role="application"',
      requirement: 'Using role="application" is generally discouraged because it disables standard screen reader modes and forces users into an application mode, removing familiar navigation shortcuts.',
      recommendation: 'Remove role="application" — it disables standard screen reader navigation shortcuts.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'NoExtraInformationInTitle',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'minor', priority: 4 },
    automation: 'deterministic',
    checks: [
      {
        id: 'general:no-extra-information-in-title-only',
        profiles: ['standards', 'commercial-parity'],
        evaluator: 'attributes-roles',
        target: { selector: '[title]' },
        options: { mode: 'title-only-primary-label' },
        classification: 'confirmed',
      },
      {
        id: 'general:no-extra-information-in-title-duplicate',
        profiles: ['standards', 'commercial-parity'],
        evaluator: 'attributes-roles',
        target: { selector: '[title]' },
        options: { mode: 'title-duplicates-visible' },
        classification: 'potential',
      },
    ],
    reporting: {
      title: 'The title attribute should not be the only method used to provide information',
      requirement: 'The title attribute is announced inconsistently across screen readers and browsers, making it unreliable for labeling interactive controls.',
      recommendation: 'Provide a visible label, aria-label, or associated label instead of relying on title alone. Remove redundant title attributes that duplicate visible text.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'FigureDiscernible',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'heuristic',
    checks: [{
      id: 'general:figure-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: 'figure' },
      options: { mode: 'figure-missing-caption' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Figure elements should receive text description or lose figure role',
      requirement: 'Figure elements are often incorrectly used to display images on the screen. Incorrectly using the figure tag, without providing a proper figcaption, adds unnecessary clutter to the screen reader user\'s experience.',
      recommendation: 'Add <figcaption> or aria-label to <figure> elements.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'AriaDescribedByHasReference',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'general:aria-describedby-has-reference',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'aria-reference',
      target: { selector: '[aria-describedby]' },
      options: { attribute: 'aria-describedby' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'aria-describedby should reference a valid element id',
      requirement: 'If an element\'s aria-describedby attribute points to an id that does not exist or is not valid, assistive technologies will not convey the intended description.',
      recommendation: 'Ensure aria-describedby references existing element IDs in the same document or shadow root.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'AriaLabelledByHasReference',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'general:aria-labelledby-has-reference',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'aria-reference',
      target: { selector: '[aria-labelledby]' },
      options: { attribute: 'aria-labelledby' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'aria-labelledby should reference a valid element id',
      requirement: 'Since aria-labelledby relies on valid id references, screen readers can only announce the label if the target exists. If the id is missing or invalid, the label will not be conveyed.',
      recommendation: 'Ensure aria-labelledby references existing element IDs in the same document or shadow root.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'StrongMismatch',
    status: 'active',
    category: 'general',
    standard: { version: 'Best Practice', level: 'n/a', criterion: 'n/a' },
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'general:strong-mismatch',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'semantic-style',
      target: { selector: 'span' },
      options: { mode: 'strong-mismatch' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Strong should be tagged properly for assistive technology',
      requirement: 'Elements with strong importance should have the strong role. If not, screen reader users may not understand the importance of the text.',
      recommendation: 'Confirm that bold styling conveys importance. If it does, use <strong>; otherwise keep the presentational markup.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'EmphasisMismatch',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'heuristic',
    checks: [
      {
        id: 'general:emphasis-mismatch',
        profiles: ['standards'],
        evaluator: 'semantic-style',
        target: { selector: 'span, i' },
        options: { mode: 'emphasis-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:emphasis-mismatch-native',
        profiles: ['commercial-parity'],
        evaluator: 'semantic-style',
        target: { selector: 'i' },
        options: { mode: 'emphasis-mismatch', nativeItalicOnly: true },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Emphasis should be tagged properly for assistive technology',
      requirement: 'Elements with emphasis importance should have the emphasis role. If not, screen reader users may not understand the emphasis of the text.',
      recommendation: 'Replace <span> with <em> for visually italic text when emphasis is intended.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'VisibilityMisuse',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'heuristic',
    checks: [
      {
        id: 'general:visibility-misuse',
        profiles: ['standards'],
        evaluator: 'semantic-style',
        target: { selector: 'a, button, input, select, textarea, p, span, h1, h2, h3, h4, h5, h6, li' },
        eligibility: { visibility: 'all' },
        options: { mode: 'visibility-misuse' },
        classification: 'potential',
      },
      {
        id: 'parity:credential-gate-visibility-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'credential-gate-visibility-misuse' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:structural-visibility-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'structural-visibility-misuse' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Visibly hidden content should not be exposed to assistive technology',
      requirement: 'When elements are visually hidden but still exposed to assistive technology, screen reader users may encounter content that should not be available in the current interface. This can obscure the current state of the page and lead to confusion about what information or controls are available.',
      recommendation: 'Review visually hidden but AT-exposed content and hide it from assistive technology when appropriate.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'VisibilityMismatch',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'deterministic',
    checks: [
      {
        id: 'general:visibility-mismatch',
        profiles: ['standards'],
        evaluator: 'standards-signal',
        target: { selector: '[aria-hidden="true"]' },
        eligibility: { visibility: 'all' },
        options: { mode: 'visibility-mismatch' },
        classification: 'confirmed',
      },
      {
        id: 'parity:aria-hidden-visible',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'aria-hidden-visible' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Visible content should not be hidden from assistive technology',
      requirement: 'If content remains visible on the screen but assigned aria-hidden="true", it will be excluded from the accessibility tree.',
      recommendation: 'Remove aria-hidden="true" from visible elements, or add a proper aria-label.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'BreadcrumbsNav',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'general:breadcrumbs-nav',
      profiles: ['standards'],
      evaluator: 'semantic-style',
      target: { selector: 'nav' },
      options: { mode: 'breadcrumbs-nav' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Breadcrumbs navigation should be tagged properly',
      requirement: 'Breadcrumb navigation regions are essential for user orientation. If not appropriately tagged, screen reader users will not know that such an option exists on the page.',
      recommendation: 'Use an <ol> list inside breadcrumb <nav> for proper screen reader announcement.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'SalePriceDiscernible',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'heuristic',
    checks: [{
      id: 'general:sale-price-discernible',
      profiles: ['standards'],
      evaluator: 'semantic-style',
      target: { selector: 'del, s, strike, span' },
      options: { mode: 'sale-price-discernible' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Original and discounted prices should be indicated to assistive technology',
      requirement: 'Discounted prices often appear next to the original and distinguished with visual cues like strikethroughs or color changes. Both prices must also be conveyed by screen readers.',
      recommendation: 'Add aria-label to distinguish original and discounted prices for screen readers.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkAnchorAmbiguous',
    status: 'active',
    category: 'general',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.4.4' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'general:link-anchor-ambiguous',
      profiles: ['standards'],
      evaluator: 'semantic-style',
      target: { selector: 'a' },
      options: { mode: 'link-anchor-ambiguous' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Ambiguous links should have additional descriptions for screen readers',
      requirement: 'Ambiguous links like empty or fragment-only href values are often used as a call to action without enough context for screen reader users.',
      recommendation: 'Replace empty/fragment-only href with a valid URL, or use <button> for actions.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
