/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'ImageDiscernible',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'graphics:image-discernible',
      profiles: ['standards'],
      evaluator: 'graphics',
      target: { selector: 'img' },
      options: { mode: 'image-discernible' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Functional images should have a text alternative',
      requirement: 'Images require a text alternative when the image conveys meaningful content or serves a functional purpose.',
      recommendation: 'Add an alt attribute to all <img> elements. Use alt="" for decorative images.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'ImageDiscernibleCorrectly',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'moderate', priority: 3 },
    automation: 'heuristic',
    checks: [{
      id: 'graphics:image-discernible-correctly',
      profiles: ['standards'],
      evaluator: 'graphics',
      target: { selector: 'img[alt]' },
      options: { mode: 'image-discernible-correctly' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Functional images should have an informative and accurate text alternative',
      requirement: 'Text alternatives must provide accurate descriptions of the image.',
      recommendation: 'Describe the image content meaningfully instead of using generic placeholder alt text.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'ImageMisuse',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'minor', priority: 4 },
    automation: 'heuristic',
    checks: [
      {
        id: 'graphics:image-misuse',
        profiles: ['standards'],
        evaluator: 'graphics',
        target: { selector: '[role="img"]' },
        options: { mode: 'image-misuse' },
        classification: 'potential',
      },
      {
        id: 'parity:symbol-image-role',
        profiles: ['commercial-parity'],
        evaluator: 'graphics',
        target: { selector: 'svg[role="img"]' },
        options: { mode: 'symbol-image-role-parity' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Only elements that function as images should be tagged as image',
      requirement: 'When non-graphical elements are marked up as images, screen reader users may misunderstand the intended purpose of the content.',
      recommendation: 'Remove role="img" from non-graphical elements.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'IconDiscernible',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'serious', priority: 6 },
    automation: 'heuristic',
    checks: [
      {
        id: 'graphics:icon-discernible',
        profiles: ['standards'],
        evaluator: 'graphics',
        target: { selector: 'svg[role="img"]' },
        options: { mode: 'icon-discernible' },
        classification: 'potential',
      },
      {
        id: 'parity:symbol-icon-discernible',
        profiles: ['commercial-parity'],
        evaluator: 'graphics',
        target: { selector: 'svg' },
        options: { mode: 'symbol-icon-discernible-parity' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Meaningful icons should have a label, while decorative icons should be hidden',
      requirement: 'Smaller graphics used as decorative or complementary elements that do not provide additional information will often add unnecessary clutter.',
      recommendation: 'Add aria-hidden="true" to decorative SVGs, or aria-label for meaningful icons.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'DecorativeGraphicExposed',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'minor', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'graphics:decorative-graphic-exposed',
      profiles: ['standards'],
      evaluator: 'graphics',
      target: { selector: 'svg, i' },
      options: { mode: 'decorative-graphic-exposed' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Decorative graphics inside interactive elements should be hidden',
      requirement: 'Small decorative icons inside interactive elements that already have text labels add unnecessary clutter to the screen reader experience.',
      recommendation: 'Add aria-hidden="true" to decorative icons inside links/buttons that already have text labels.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'BackgroundImageDiscernibleImage',
    status: 'active',
    category: 'graphics',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.1.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'graphics:background-image-discernible',
      profiles: ['standards'],
      evaluator: 'graphics',
      target: { selector: '*', allowPluginFallback: true },
      options: { mode: 'background-image-discernible' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Functional CSS background images should be tagged for assistive technology',
      requirement: 'Functional images presented using CSS background properties should be marked up using role="img" so that they can be identified as images by screen reader users.',
      recommendation: 'Add role="img" and aria-label to functional CSS background images.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
