const BP = { version: 'Best Practice', level: 'n/a', criterion: 'n/a' };

/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'ButtonDiscernible',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:button-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'accessible-name',
      target: { selector: 'button' },
      options: { mode: 'button-missing-name' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Buttons should have a label',
      requirement: 'Buttons that do not contain visible text should be assigned labels that inform screen reader users of their purpose.',
      recommendation: 'Add text content, aria-label, or title to <button> elements.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'LinkAnchorDiscernible',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.4.4' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:link-anchor-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'accessible-name',
      target: { selector: 'a[href^="#"]' },
      options: { mode: 'anchor-link-missing-name' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Anchor links should have a descriptive label',
      requirement: 'Activating anchor links enables users to navigate to a different section within the same page. Anchor links without visible text or labeled images should be assigned labels that inform screen reader users of their destination.',
      recommendation: 'Add visible text or aria-label to anchor links so screen readers announce their destination.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'LinkNavigationDiscernible',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:link-navigation-discernible',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'accessible-name',
      target: { selector: 'a[href]' },
      options: { mode: 'nav-link-missing-name' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Navigation links should have a descriptive label',
      requirement: 'Activating navigation links enables users to navigate to a different page within the site. Links without visible text or labeled images should be assigned labels.',
      recommendation: 'Add visible text or aria-label to navigation links.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'LinkOpensNewWindow',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'AAA', criterion: '3.2.5' },
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:link-opens-new-window',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'link-warnings',
      target: { selector: 'a[target="_blank"]' },
      options: { mode: 'new-window' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Warning a user when a link opens in a new window is recommended',
      requirement: 'It\'s good practice to warn users about the expected behavior when activating a link opens a new browser window or tab.',
      recommendation: 'Add "(opens in new window)" to aria-label or visible text for target="_blank" links.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'NoAutofocus',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '3.2.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:no-autofocus',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[autofocus]' },
      options: { mode: 'has-autofocus' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Avoid using autofocus',
      requirement: 'Make sure that no element has an autofocus attribute.',
      recommendation: 'Remove autofocus attribute — it causes unexpected focus movement for screen reader users.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'MenuTriggerClickable',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.1.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:menu-trigger-clickable',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[aria-haspopup]' },
      options: { mode: 'haspopup-not-interactive' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'ARIA relationship attributes should only be applied to elements with appropriate roles',
      requirement: 'Interactive elements that trigger additional content should only have relationship and state ARIA attributes if they have interactive roles, such as button, tab, or combobox.',
      recommendation: 'Menu trigger must be a <button> or have tabindex and role="button" for keyboard access.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'MenuAvoid',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:menu-avoid',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[role="menu"]' },
      options: { mode: 'menu-on-navigation' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Avoid using role="menu" for web navigation links',
      requirement: 'In most cases, using role=menu on navigation elements within a web page can negatively impact screen reader users, especially those using JAWS.',
      recommendation: 'Remove role="menu" from web navigation — use role="menu" only for desktop-style app menus.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'MenuBarAvoid',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:menubar-avoid',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[role="menubar"]' },
      options: { mode: 'menubar-on-navigation' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Avoid using role="menubar" for web navigation links',
      requirement: 'In most cases, using role=menubar on navigation elements within a web page can negatively impact screen reader users, especially those using JAWS.',
      recommendation: 'Remove role="menubar" from web navigation — use only for desktop-style app menus.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'MenuItemAvoid',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:menuitem-avoid',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'attributes-roles',
      target: { selector: '[role="menuitem"]' },
      options: { mode: 'menuitem-on-navigation' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Avoid using role="menuitem" for web navigation links',
      requirement: 'In most cases, using ARIA menu roles within a web page can negatively impact screen reader users, especially those using JAWS.',
      recommendation: 'Remove role="menuitem" from navigation links — use only for desktop-style app menus.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'AriaControlsHasReference',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'interactive:aria-controls-has-reference',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'aria-reference',
      target: { selector: '[aria-controls]' },
      options: { attribute: 'aria-controls' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'aria-controls should reference a valid element id',
      requirement: 'The element\'s aria-controls points to an id that does not exist, breaking the link between the controlling element and the content it manages.',
      recommendation: 'Ensure aria-controls references an existing element ID in the same document or shadow root.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkImageWarning',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:link-image-warning',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'link-warnings',
      target: { selector: 'a[href]' },
      options: { mode: 'image-href' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Warning a user when a link triggers an image to open is recommended',
      requirement: 'It\'s good practice to warn users about the expected behavior when activating a link triggers an image to appear.',
      recommendation: 'Warn users that this link opens an image.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkMailtoWarning',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:link-mailto-warning',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'link-warnings',
      target: { selector: 'a[href^="mailto:"]' },
      options: { mode: 'mailto-href' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Warning a user when a link triggers a mail application is recommended',
      requirement: 'It\'s good practice to warn users about the expected behavior when activating a link triggers a mail application.',
      recommendation: 'Warn users that this link opens a mail application.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkPDFWarning',
    status: 'active',
    category: 'interactive',
    standard: BP,
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:link-pdf-warning',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'link-warnings',
      target: { selector: 'a[href]' },
      options: { mode: 'pdf-href' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Warning a user when a link triggers a PDF file is recommended',
      requirement: 'It\'s good practice to warn users about the expected behavior when activating a link triggers a PDF reader.',
      recommendation: 'Warn users that this link opens a PDF file.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'ButtonMismatch',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:button-mismatch',
      profiles: ['standards'],
      evaluator: 'interactive-semantics',
      target: { selector: 'a, span' },
      options: { mode: 'button-mismatch' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Buttons should be tagged for assistive technology',
      requirement: 'If interactive elements cannot be identified as buttons, screen reader users may not realize the element is actionable.',
      recommendation: 'Add role="button" to <a> elements styled as buttons, or change to <button>.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkCurrentPage',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:link-current-page',
      profiles: ['standards'],
      evaluator: 'link-destination',
      target: { selector: 'a[href]' },
      options: { mode: 'link-current-page' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Visual indication that a link\'s destination is the current page should be announced by screen readers',
      requirement: 'Visual cues are often used by sighted users to indicate which link represents the current page. This information should be made available to screen reader users.',
      recommendation: 'Add aria-current="page" to links pointing to the current page.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'LinkNavigationAmbiguous',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.4.4' },
    severity: { impact: 'serious', priority: 5 },
    automation: 'heuristic',
    checks: [
      {
        id: 'interactive:link-navigation-ambiguous',
        profiles: ['standards'],
        evaluator: 'link-destination',
        target: { selector: 'a[href]' },
        options: { mode: 'link-navigation-ambiguous' },
        classification: 'potential',
      },
      {
        id: 'parity:current-link-destination-ambiguous',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        target: { selector: 'a[href]' },
        options: { mode: 'current-link-destination-ambiguous' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:repeated-link-destination-ambiguous',
        profiles: ['commercial-parity'],
        evaluator: 'link-destination',
        target: { selector: 'a[href]' },
        options: { mode: 'link-navigation-ambiguous-parity' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Link context should be exposed to assistive technology',
      requirement: 'Screen reader users may find it difficult to distinguish between links when the purpose of each link cannot be determined from its text alone.',
      recommendation: 'Add unique aria-label to distinguish links with identical text pointing to different destinations.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TargetSize',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.2', level: 'AA', criterion: '2.5.8' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'interactive:target-size',
      profiles: ['standards'],
      evaluator: 'geometry',
      target: { selector: 'a[href], button, input, select, textarea, [role="button"]' },
      options: { mode: 'target-size' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Interactive targets should be 24×24 CSS pixels or qualify for a spacing exception',
      requirement: 'WCAG 2.5.8 requires targets to be at least 24×24 CSS pixels unless they qualify for a spacing, inline, user-agent, or essential exception. This automated check detects undersized targets whose centered 24px spacing circles overlap a nearby target\'s spacing circle.',
      recommendation: 'Increase the target to at least 24×24 CSS pixels, add spacing so 24px circles do not overlap nearby targets, or confirm an inline, user-agent, or essential exception applies.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'FocusNotObscuredFooter',
    status: 'active',
    category: 'interactive',
    standard: { version: 'WCAG 2.2', level: 'AA', criterion: '2.4.11' },
    severity: { impact: 'critical', priority: 1 },
    automation: 'behavioral',
    checks: [{
      id: 'interactive:focus-not-obscured-footer',
      profiles: ['standards'],
      evaluator: 'focus-obscuration',
      options: { mode: 'focus-not-obscured-footer' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Focused elements should not be obscured by a sticky footer',
      requirement: 'A sticky footer remains anchored to the bottom of the screen while the rest of the page content can be scrolled. If it is not offset from interactive elements, it can overlap and obscure the item in focus.',
      recommendation: 'Add bottom padding so focused elements are never hidden behind the sticky footer.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
