/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'NavigationMisuse',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 6 },
    automation: 'heuristic',
    checks: [{
      id: 'landmarks:navigation-misuse',
      profiles: ['standards'],
      evaluator: 'landmark-graph',
      target: { selector: 'nav, [role="navigation"]', allowPluginFallback: true },
      options: { mode: 'navigation-misuse' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Navigation landmark does not contain key site navigation links',
      requirement: 'A navigation landmark should identify a section that contains primary links for moving through the site or page.',
      recommendation: 'Confirm this landmark contains key site navigation links and use list markup when the links form a list.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'SearchFormMismatch',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'Best Practice', level: 'n/a', criterion: 'n/a' },
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:search-form-mismatch',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        target: { selector: 'form' },
        options: { mode: 'search-form-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:search-without-landmark',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'search-without-landmark' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'A search form should be tagged as a search landmark',
      requirement: 'Screen reader users rely on landmarks to quickly access important regions of a page.',
      recommendation: 'Confirm this is a search region, then add role="search" or wrap it in a <search> element.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionFooterMisuse',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'Best Practice', level: 'n/a', criterion: 'n/a' },
    severity: { impact: 'moderate', priority: 6 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:region-footer-misuse',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        target: { selector: 'footer, [role="contentinfo"]' },
        options: { mode: 'region-footer-misuse' },
        classification: 'potential',
      },
      {
        id: 'parity:separated-footer-region-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'separated-footer-region-misuse' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:wrapped-footer-region-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'wrapped-footer-region-misuse' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'An element without global site information is tagged as a contentinfo landmark',
      requirement: 'When a region without global site information is tagged as a contentinfo landmark, screen reader users may be misled about its purpose.',
      recommendation: 'Remove role="contentinfo" from non-footer elements.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionFooterSingle',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'Best Practice', level: 'n/a', criterion: 'n/a' },
    severity: { impact: 'moderate', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'landmarks:region-footer-single',
      profiles: ['standards'],
      evaluator: 'landmark-graph',
      options: { mode: 'region-footer-single' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Each page should include at most one global contentinfo landmark (footer)',
      requirement: 'Each page should normally include only one contentinfo landmark to keep landmark navigation simple and predictable.',
      recommendation: 'Remove duplicate contentinfo landmarks.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionFooterMismatch',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 6 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:region-footer-mismatch',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        target: { selector: 'body' },
        options: { mode: 'region-footer-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:separated-footer-region-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'separated-footer-region-mismatch' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:wrapped-footer-region-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'wrapped-footer-region-mismatch' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Global site information should be in a contentinfo landmark (footer)',
      requirement: 'The contentinfo region provides screen reader users with information about the website, such as copyright, contact details, and legal information.',
      recommendation: 'Add global site information or remove the contentinfo landmark.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'ArticleMisuse',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'landmarks:article-misuse',
      profiles: ['standards'],
      evaluator: 'landmark-graph',
      target: { selector: 'article' },
      options: { mode: 'article-misuse' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Only elements that function as articles should be tagged as article regions',
      requirement: 'Using an <article> tag on content that is not self-contained causes screen readers to announce misleading information about the page structure.',
      recommendation: 'Remove <article> from non-self-contained content or add heading.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'BreadcrumbsMismatch',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:breadcrumbs-mismatch',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        target: { selector: 'nav' },
        options: { mode: 'breadcrumbs-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:nav-submenu-breadcrumbs',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'nav-submenu-breadcrumbs' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Breadcrumb navigation region should have a label',
      requirement: 'A breadcrumb region presents a trail of links showing the user\'s current page in relation to higher-level pages on a site.',
      recommendation: 'Add aria-label="Breadcrumb" to the breadcrumb <nav> element.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionMainContentSingle',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'deterministic',
    checks: [{
      id: 'landmarks:region-main-single',
      profiles: ['standards'],
      evaluator: 'landmark-graph',
      options: { mode: 'region-main-single' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Each page should include at most one main landmark',
      requirement: 'A page typically presents one central subject, so a single main landmark establishes the boundaries of the primary content for screen reader users.',
      recommendation: 'Use only one <main> landmark per page.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionMainContentMisuse',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:region-main-misuse',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        target: { selector: 'main, [role="main"]' },
        options: { mode: 'region-main-misuse' },
        classification: 'potential',
      },
      {
        id: 'parity:credential-gate-region-main-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'credential-gate-region-main-misuse' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:nested-main-boundary-misuse',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'nested-main-boundary-misuse' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'An element without main content is tagged as a main landmark',
      requirement: 'Incorrectly tagging the main landmark may cause screen reader users to misunderstand where the primary content begins or ends.',
      recommendation: 'Remove <main> from minimal content or add primary page content.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'RegionMainContentMismatch',
    status: 'active',
    category: 'landmarks',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [
      {
        id: 'landmarks:region-main-mismatch',
        profiles: ['standards'],
        evaluator: 'landmark-graph',
        options: { mode: 'region-main-mismatch' },
        classification: 'potential',
      },
      {
        id: 'parity:credential-gate-region-main-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'credential-gate-region-main-mismatch' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'All main content should be contained in the main landmark',
      requirement: 'The main landmark represents the primary content of a page and should include content unique to that page.',
      recommendation: 'Move significant content inside the <main> landmark so screen readers can locate it.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
