const BP = { version: 'Best Practice', level: 'n/a', criterion: 'n/a' };

/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'HtmlLang',
    status: 'active',
    category: 'metadata',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '3.1.1' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:html-lang',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'html-lang-missing' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Default page language should be defined',
      requirement: 'Specifying a default page language ensures screen readers apply the correct pronunciation rules, voices, and braille output.',
      recommendation: 'Add lang attribute to the <html> element (e.g. lang="en").',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'HtmlLangValid',
    status: 'active',
    category: 'metadata',
    standard: BP,
    severity: { impact: 'moderate', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:html-lang-valid',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'html-lang-invalid' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'HTML lang attribute should have a valid value',
      requirement: 'Assigning a valid ISO language value to the <html> lang attribute ensures that screen readers use the correct pronunciation rules.',
      recommendation: 'Use a standard ISO 639-1 language code such as "en".',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'MetaDescription',
    status: 'active',
    category: 'metadata',
    standard: BP,
    severity: { impact: 'minor', priority: 5 },
    automation: 'heuristic',
    checks: [{
      id: 'metadata:meta-description',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'meta-description-missing' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Page should have a meta description',
      requirement: 'A meta description provides a brief summary of the page content for search engines and assistive technologies.',
      recommendation: 'Add <meta name="description" content="..."> for SEO and accessibility.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'MetaRefresh',
    status: 'active',
    category: 'metadata',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.2.1' },
    severity: { impact: 'critical', priority: 1 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:meta-refresh',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'meta-refresh-present' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Pages should not use meta http-equiv="refresh"',
      requirement: 'A <meta> element with http-equiv="refresh" is sometimes used to automatically redirect users after a time delay. These timed changes can interrupt and disorient users who rely on assistive technology.',
      recommendation: 'Remove meta http-equiv="refresh" — use server-side redirects instead.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'MetaViewportPresent',
    status: 'active',
    category: 'metadata',
    standard: BP,
    severity: { impact: 'moderate', priority: 4 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:meta-viewport-present',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'meta-viewport-missing' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Page should have a meta viewport tag',
      requirement: 'Providing a meta viewport to control layout and scaling on mobile devices.',
      recommendation: 'Add <meta name="viewport" content="width=device-width, initial-scale=1"> for proper mobile layout.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'MetaViewportScalable',
    status: 'active',
    category: 'metadata',
    standard: { version: 'WCAG 2.0', level: 'AA', criterion: '1.4.4' },
    severity: { impact: 'critical', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:meta-viewport-scalable',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'meta-viewport-not-scalable' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Meta viewport should allow content scaling',
      requirement: 'The meta viewport should allow scalability so text can be resized up to 200% without loss of functionality. Using user-scalable=no or maximum-scale=1 prevents users from enlarging content.',
      recommendation: 'Remove user-scalable=no and ensure maximum-scale allows resizing to at least 200%. A maximum-scale of 5.0 or higher provides stronger guidance.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'PageTitle',
    status: 'active',
    category: 'metadata',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.4.2' },
    severity: { impact: 'serious', priority: 2 },
    automation: 'deterministic',
    checks: [{
      id: 'metadata:page-title',
      profiles: ['standards', 'commercial-parity'],
      evaluator: 'document-metadata',
      options: { mode: 'page-title-missing' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Page should have a title',
      requirement: 'A missing page title makes it difficult for screen reader users and sighted users with multiple tabs open to identify the page.',
      recommendation: 'Add a <title> element to the page head.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'PageTitleDescriptive',
    status: 'active',
    category: 'metadata',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '2.4.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'heuristic',
    checks: [
      {
        id: 'metadata:page-title-descriptive',
        profiles: ['standards'],
        evaluator: 'document-metadata',
        options: { mode: 'page-title-not-descriptive' },
        classification: 'potential',
      },
      {
        id: 'parity:credential-gate-page-title',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'credential-gate-page-title' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Page title should be descriptive',
      requirement: 'Screen readers rely heavily on page titles to announce the purpose of a page. If titles aren’t descriptive, users with low or no vision may not understand the context until they start navigating the page.',
      recommendation: 'Add a descriptive, unique page title.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
