/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'TableHeaders',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'heuristic',
    checks: [{
      id: 'tables:table-headers',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'table' },
      options: { mode: 'table-headers' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Table column headers should be tagged for assistive technology',
      requirement: 'If a column header is not marked up with the correct role or scope, screen reader users cannot determine which header applies to each cell.',
      recommendation: 'Add <th> header cells to data tables for screen reader row/column association.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TableNesting',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tables:table-nesting',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'table' },
      options: { mode: 'table-nesting' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Tables should not be nested',
      requirement: 'Nested tables are often misinterpreted by screen readers, making it hard for users to follow the intended structure and meaning of the data.',
      recommendation: 'Flatten nested tables — screen readers struggle with nested table structures.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TableRoles',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'tables:table-roles',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: '[role="table"], [role="grid"]' },
      options: { mode: 'table-roles' },
      classification: 'potential',
    }],
    reporting: {
      title: 'ARIA tables should follow the documented table hierarchy',
      requirement: 'ARIA table, grid, row, and cell roles should follow the documented hierarchy so screen readers can announce row and column relationships correctly.',
      recommendation: 'Use role="row", role="rowgroup", and role="cell"/"columnheader"/"rowheader" inside ARIA tables.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TableCaption',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'tables:table-caption',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'table' },
      options: { mode: 'table-caption' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Data tables should have a caption',
      requirement: 'A caption or aria-label on data tables provides screen readers with context about the table\'s purpose and content.',
      recommendation: 'Add <caption> or aria-label to data tables.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TableHeaderEmpty',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tables:table-header-empty',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'th' },
      options: { mode: 'table-header-empty' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Table header cells should not be empty',
      requirement: 'If a table header cell is empty, screen reader users may only hear a generic label such as "column 3" or nothing at all.',
      recommendation: 'Add descriptive header text to empty <th> cells.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TableMisuse',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'tables:table-misuse',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'table' },
      options: { mode: 'table-misuse' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Only elements that function as data tables should be tagged as table',
      requirement: 'When a layout table is marked up with HTML table elements or assigned table ARIA roles, screen readers announce a data table structure even though the table is only used for page layout.',
      recommendation: 'Remove data-table semantics from layout tables or use CSS for layout.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TableRowHeaderMismatch',
    status: 'active',
    category: 'tables',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '1.3.1' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'heuristic',
    checks: [{
      id: 'tables:table-row-header-mismatch',
      profiles: ['standards'],
      evaluator: 'table-graph',
      target: { selector: 'th' },
      options: { mode: 'table-row-header-mismatch' },
      classification: 'potential',
    }],
    reporting: {
      title: 'Table row headers should be tagged for assistive technology',
      requirement: 'If a table row header is not marked up with the correct role or scope, screen reader users cannot determine which header applies to each cell.',
      recommendation: 'Add scope="row" to row header cells.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
];
