/** @type {import('../engine/schema.js').RuleDescriptor[]} */
export default [
  {
    id: 'TablistRole',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [
      {
        id: 'tabs:tablist-role-explicit',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tablist-role-explicit' },
        classification: 'confirmed',
      },
      {
        id: 'tabs:tablist-role-inferred',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tablist-role-inferred' },
        classification: 'potential',
      },
      {
        id: 'parity:disclosure-tablist-role',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'disclosure-tablist-role' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:visual-state-tablist-role',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'visual-state-tablist-role' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Tablists should be tagged for assistive technology',
      requirement: 'A tablist without role="tablist" is not announced as a group of related tabs, which prevents screen reader users from recognizing the structure and purpose of the component. This makes it harder to navigate between tabs and understand that the controls belong to a single set.',
      recommendation: 'Wrap the tab controls in a container with role="tablist".',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TabAriaSelected',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tab-aria-selected',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tab-aria-selected' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Tab elements should have aria-selected',
      requirement: 'Tab elements need aria-selected to communicate which tab is currently active to screen reader users.',
      recommendation: 'Add aria-selected to tab elements.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TabAriaControls',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tab-aria-controls',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tab-aria-controls' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Tab elements should have aria-controls',
      requirement: 'Tab elements need aria-controls pointing to the tabpanel ID so screen readers can link tabs to their content panels.',
      recommendation: 'Add aria-controls pointing to the tabpanel ID.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TabListMisuse',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tablist-misuse',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tablist-misuse' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Only elements that function as tablists should receive role="tablist"',
      requirement: 'Applying role="tablist" to an element without tabs misleads screen reader users by suggesting a group of tabs that does not exist.',
      recommendation: 'Remove role="tablist" or add proper tab children.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TabMismatch',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [
      {
        id: 'tabs:tab-mismatch-explicit',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tab-mismatch-explicit' },
        classification: 'confirmed',
      },
      {
        id: 'tabs:tab-mismatch-inferred',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tab-mismatch-inferred' },
        classification: 'potential',
      },
      {
        id: 'parity:disclosure-tab-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'disclosure-tab-mismatch' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:visual-state-tab-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'visual-state-tab-mismatch' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Tab controls should be tagged for assistive technology',
      requirement: 'Custom tabs must be explicitly defined for screen readers since there are no native HTML tab elements. Without assigning role="tab" to the interactive elements, assistive technology will not identify them as tabs, preventing users from understanding their function or navigating them as part of a tab interface.',
      recommendation: 'Add role="tab" and the required selected/focus states.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TabMisuse',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tab-misuse',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tab-misuse' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Only elements that function as tabs should receive role="tab"',
      requirement: 'Applying role="tab" to an element that is not part of a functioning tab interface misleads screen reader users.',
      recommendation: 'Remove role="tab" from elements outside a tablist.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TabPanelMismatch',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [
      {
        id: 'tabs:tab-panel-mismatch-explicit',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tab-panel-mismatch-explicit' },
        classification: 'confirmed',
      },
      {
        id: 'tabs:tab-panel-mismatch-inferred',
        profiles: ['standards'],
        evaluator: 'tab-graph',
        options: { mode: 'tab-panel-mismatch-inferred' },
        classification: 'potential',
      },
      {
        id: 'parity:disclosure-tab-panel-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'disclosure-tab-panel-mismatch' },
        classification: 'commercial-parity',
      },
      {
        id: 'parity:visual-state-tab-panel-mismatch',
        profiles: ['commercial-parity'],
        evaluator: 'commercial-parity',
        options: { mode: 'visual-state-tab-panel-mismatch' },
        classification: 'commercial-parity',
      },
    ],
    reporting: {
      title: 'Tab panels should be tagged for assistive technology',
      requirement: 'The role="tabpanel" identifies an element as the content region of a tab interface.',
      recommendation: 'Add role="tabpanel" and label it from its controlling tab.',
    },
    fix: { deterministic: false, policy: 'manual_only' },
  },
  {
    id: 'TabPanelMisuse',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'serious', priority: 3 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tab-panel-misuse',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tab-panel-misuse' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Only elements that function as tab panels should receive role="tabpanel"',
      requirement: 'Applying role="tabpanel" to an element without a corresponding tab misleads screen reader users.',
      recommendation: 'Remove role="tabpanel" or associate it with a controlling tab.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
  {
    id: 'TabpanelLabelledBy',
    status: 'active',
    category: 'tabs',
    standard: { version: 'WCAG 2.0', level: 'A', criterion: '4.1.2' },
    severity: { impact: 'moderate', priority: 4 },
    automation: 'deterministic',
    checks: [{
      id: 'tabs:tabpanel-labelledby',
      profiles: ['standards'],
      evaluator: 'tab-graph',
      options: { mode: 'tabpanel-labelledby' },
      classification: 'confirmed',
    }],
    reporting: {
      title: 'Tab panels should have aria-labelledby',
      requirement: 'Tab panels need aria-labelledby referencing the controlling tab element ID for screen reader navigation.',
      recommendation: 'Add aria-labelledby referencing the controlling tab element ID.',
    },
    fix: { deterministic: true, policy: 'mechanically_safe' },
  },
];
