import { mkdtempSync, rmSync, mkdirSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { CORPUS_SCHEMA_VERSION } from '../../../src/scanner/access-scan/corpus/constants.js';
import {
  validateCorpusCase,
} from '../../../src/scanner/access-scan/corpus/schema.js';
import { alignFindingsToSnapshot } from './align.js';
import { captureStableSnapshot, normalizeCapturedSnapshot } from './capture.js';
import { CorpusToolingError, CORPUS_TOOLING_ERROR_CODES } from './errors.js';
import {
  ingestAccessScanReport,
  normalizeReportFindings,
} from './ingest.js';
import { resolveDraftDir, reassertDraftPathSafe } from './paths.js';
import {
  assertNoRedactionLeaks,
  sanitizeSnapshot,
} from './sanitize.js';

const __draftDirname = path.dirname(fileURLToPath(import.meta.url));
const DRAFT_VALIDATION_TMP_ROOT = path.resolve(__draftDirname, '../../../.tmp-accessscan-corpus-tests');
mkdirSync(DRAFT_VALIDATION_TMP_ROOT, { recursive: true });

/** @type {{ reassert: (draftDir: string) => string } | null} */
let draftPathGuardOverride = null;

/**
 * @param {{ reassert: (draftDir: string) => string } | null} guard
 */
export function setDraftPathGuardForTests(guard) {
  draftPathGuardOverride = guard;
}

export function resetDraftPathGuardForTests() {
  draftPathGuardOverride = null;
}

/**
 * @typedef {object} DraftCaseRequest
 * @property {string} id
 * @property {string} draftDir
 * @property {Record<string, unknown>} report
 * @property {() => Promise<Record<string, unknown>> | Record<string, unknown>} captureAdapter
 * @property {string=} pageHtml
 * @property {boolean=} overwrite
 * @property {(page: unknown, context: Record<string, unknown>) => Promise<void>=} stateAdapter
 * @property {{ reassert: (draftDir: string) => string }=} pathGuard
 * @property {Set<string>=} allowedRuleIds
 */

/**
 * @param {string} draftDir
 * @param {Record<string, string>} serialized
 * @param {boolean} overwrite
 * @param {{ reassert: (draftDir: string) => string }=} pathGuard
 * @returns {Promise<string[]>}
 */
async function writeDraftFilesExclusive(draftDir, serialized, overwrite, pathGuard) {
  const guard = pathGuard || draftPathGuardOverride || { reassert: reassertDraftPathSafe };

  guard.reassert(draftDir);
  await mkdir(draftDir, { recursive: true });
  /** @type {string[]} */
  const written = [];

  try {
    for (const [fileName, content] of Object.entries(serialized)) {
      guard.reassert(draftDir);
      const filePath = path.join(draftDir, fileName);
      const flag = overwrite ? 'w' : 'wx';
      await writeFile(filePath, `${content}\n`, { encoding: 'utf8', flag });
      written.push(filePath);
    }
  } catch (error) {
    await Promise.all(written.map((filePath) => rm(filePath, { force: true })));
    if (!overwrite && written.length === 0) {
      await rm(draftDir, { recursive: true, force: true }).catch(() => {});
    }
    if (/** @type {NodeJS.ErrnoException} */ (error).code === 'EEXIST') {
      throw new CorpusToolingError(
        CORPUS_TOOLING_ERROR_CODES.OUTPUT_EXISTS,
        'Draft file already exists',
        { filePath: written.at(-1) || draftDir },
      );
    }
    throw error;
  }

  return Object.keys(serialized);
}

/**
 * @param {DraftCaseRequest} request
 * @returns {Promise<{
 *   draftDir: string,
 *   files: string[],
 *   meta: Record<string, unknown>,
 *   snapshot: Record<string, unknown>,
 *   expected: Record<string, unknown>,
 * }>}
 */
export async function generateDraftCase(request) {
  const draftDir = resolveDraftDir(request.draftDir);
  const overwrite = Boolean(request.overwrite);

  const report = ingestAccessScanReport(request.report);
  const normalizedFindings = await normalizeReportFindings(report, {
    allowedRuleIds: request.allowedRuleIds,
  });
  const rawSnapshot = await captureStableSnapshot({
    captureAdapter: request.captureAdapter,
    route: report.route,
    captureState: report.pageState,
    viewport: report.viewport,
    stateAdapter: request.stateAdapter,
  });
  const normalizedSnapshot = normalizeCapturedSnapshot(rawSnapshot);
  const sanitizedSnapshot = sanitizeSnapshot(normalizedSnapshot);
  const alignedFindings = alignFindingsToSnapshot(sanitizedSnapshot, normalizedFindings);

  const meta = {
    schemaVersion: CORPUS_SCHEMA_VERSION,
    id: request.id,
    profile: report.profile,
    route: report.route,
    captureState: report.pageState,
    viewport: report.viewport,
    notes: [
      'Draft corpus case generated by accessscan-corpus tooling.',
    ],
  };

  const expected = {
    schemaVersion: CORPUS_SCHEMA_VERSION,
    profile: report.profile,
    findings: alignedFindings,
  };

  const serialized = {
    'meta.json': JSON.stringify(meta, null, 2),
    'snapshot.json': JSON.stringify(sanitizedSnapshot, null, 2),
    'expected.json': JSON.stringify(expected, null, 2),
    ...(typeof request.pageHtml === 'string'
      ? { 'page.html': request.pageHtml }
      : {}),
  };

  assertNoRedactionLeaks(serialized);

  const tempDir = mkdtempSync(path.join(DRAFT_VALIDATION_TMP_ROOT, 'ada-corpus-draft-'));
  try {
    await validateDraftSerialized(serialized, tempDir);
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }

  const files = await writeDraftFilesExclusive(
    draftDir,
    serialized,
    overwrite,
    request.pathGuard || draftPathGuardOverride || undefined,
  );

  return {
    draftDir,
    files,
    meta,
    snapshot: sanitizedSnapshot,
    expected,
  };
}

/**
 * Validate draft by writing to temp and using schema validator.
 *
 * @param {Record<string, string>} serialized
 * @param {string} tempDir
 */
export async function validateDraftSerialized(serialized, tempDir) {
  await mkdir(tempDir, { recursive: true });
  for (const [fileName, content] of Object.entries(serialized)) {
    if (!['meta.json', 'snapshot.json', 'expected.json', 'page.html'].includes(fileName)) continue;
    await writeFile(path.join(tempDir, fileName), `${content}\n`, 'utf8');
  }
  const result = validateCorpusCase(tempDir);
  if (!result.ok) {
    throw new CorpusToolingError(
      CORPUS_TOOLING_ERROR_CODES.SCHEMA_FAILURE,
      result.errors[0],
      { errors: result.errors },
    );
  }
  return result;
}
